//! Seek-bar thumbnails generated by one persistent in-process libmpv worker.
//!
//! The player URL and its exact request headers are supplied with every job.
//! No credentials are written to disk or retained in cache keys; only their
//! hash is kept. Two-second buckets keep scrubbing responsive without decoding
//! a new frame for every pointer pixel.

use std::{
    collections::{VecDeque, hash_map::DefaultHasher},
    ffi::{CString, c_char, c_void},
    fs,
    hash::{Hash, Hasher},
    path::{Path, PathBuf},
    ptr,
    sync::{
        Mutex, OnceLock,
        mpsc::{self, Receiver, SyncSender, TrySendError},
    },
    thread,
    time::{Duration, Instant},
};

use anyhow::{Context, Result, bail};
use libloading::Library;

const THUMBNAIL_WIDTH: i32 = 320;
const THUMBNAIL_BUCKET_MS: i64 = 2_000;
const CAPTURE_TIMEOUT: Duration = Duration::from_secs(6);
const FRAME_CACHE_LIMIT: usize = 160;

static FRAME_CACHE: OnceLock<Mutex<ThumbnailCache>> = OnceLock::new();
static WORKER: OnceLock<ThumbnailWorker> = OnceLock::new();

#[derive(Clone)]
struct CachedFrame {
    key: u64,
    source_key: u64,
    bucket: i64,
    bytes: Vec<u8>,
}

#[derive(Default)]
struct ThumbnailCache {
    frames: VecDeque<CachedFrame>,
}

impl ThumbnailCache {
    fn exact(&mut self, key: u64) -> Option<Vec<u8>> {
        let index = self.frames.iter().position(|frame| frame.key == key)?;
        let frame = self.frames.remove(index)?;
        let bytes = frame.bytes.clone();
        self.frames.push_back(frame);
        Some(bytes)
    }

    fn nearest(&mut self, source_key: u64, bucket: i64) -> Option<Vec<u8>> {
        let index = self
            .frames
            .iter()
            .enumerate()
            .filter(|(_, frame)| frame.source_key == source_key)
            .min_by_key(|(_, frame)| frame.bucket.abs_diff(bucket))
            .map(|(index, _)| index)?;
        let frame = self.frames.remove(index)?;
        let bytes = frame.bytes.clone();
        self.frames.push_back(frame);
        Some(bytes)
    }

    fn insert(&mut self, frame: CachedFrame) {
        if let Some(index) = self.frames.iter().position(|old| old.key == frame.key) {
            self.frames.remove(index);
        }
        self.frames.push_back(frame);
        while self.frames.len() > FRAME_CACHE_LIMIT {
            self.frames.pop_front();
        }
    }
}

fn cache() -> &'static Mutex<ThumbnailCache> {
    FRAME_CACHE.get_or_init(|| Mutex::new(ThumbnailCache::default()))
}

fn source_key(url: &str, request_headers: &[String]) -> u64 {
    let mut hasher = DefaultHasher::new();
    url.hash(&mut hasher);
    request_headers.hash(&mut hasher);
    hasher.finish()
}

fn bucket(position_ms: i64) -> i64 {
    position_ms.max(0) / THUMBNAIL_BUCKET_MS
}

fn frame_key(source_key: u64, bucket: i64) -> u64 {
    let mut hasher = DefaultHasher::new();
    source_key.hash(&mut hasher);
    bucket.hash(&mut hasher);
    hasher.finish()
}

struct ThumbnailRequest {
    url: String,
    request_headers: Vec<String>,
    source_key: u64,
    bucket: i64,
    key: u64,
    reply: Option<mpsc::Sender<std::result::Result<Vec<u8>, String>>>,
}

struct ThumbnailWorker {
    sender: SyncSender<ThumbnailRequest>,
}

impl ThumbnailWorker {
    fn spawn(dll_path: PathBuf) -> Self {
        // One pending slot prevents a quick pointer sweep from building a long
        // queue of frames the user no longer wants.
        let (sender, receiver) = mpsc::sync_channel(1);
        let _ = thread::Builder::new()
            .name("nuvio-thumbnail-mpv".to_string())
            .spawn(move || worker_loop(dll_path, receiver));
        Self { sender }
    }
}

/// Returns an exact cached bucket when possible. If another frame for this
/// source exists, it is returned immediately while the worker generates the
/// requested bucket in the background. The first request waits for its frame.
pub fn capture(
    dll_path: &PathBuf,
    url: &str,
    request_headers: &[String],
    position_ms: i64,
) -> Result<Vec<u8>> {
    let source_key = source_key(url, request_headers);
    let bucket = bucket(position_ms);
    let key = frame_key(source_key, bucket);
    if let Ok(mut cache) = cache().lock()
        && let Some(bytes) = cache.exact(key)
    {
        return Ok(bytes);
    }

    let nearest = cache()
        .lock()
        .ok()
        .and_then(|mut cache| cache.nearest(source_key, bucket));
    let worker = WORKER.get_or_init(|| ThumbnailWorker::spawn(dll_path.clone()));
    let (reply, response) = mpsc::channel();
    let request = ThumbnailRequest {
        url: url.to_string(),
        request_headers: request_headers.to_vec(),
        source_key,
        bucket,
        key,
        reply: nearest.is_none().then_some(reply),
    };

    if let Some(bytes) = nearest {
        match worker.sender.try_send(request) {
            Ok(()) | Err(TrySendError::Full(_)) => return Ok(bytes),
            Err(TrySendError::Disconnected(_)) => bail!("thumbnail worker stopped"),
        }
    }

    worker
        .sender
        .send(request)
        .map_err(|_| anyhow::anyhow!("thumbnail worker stopped"))?;
    response
        .recv_timeout(CAPTURE_TIMEOUT + Duration::from_secs(1))
        .map_err(|_| anyhow::anyhow!("timed out waiting for thumbnail worker"))?
        .map_err(anyhow::Error::msg)
}

fn worker_loop(dll_path: PathBuf, receiver: Receiver<ThumbnailRequest>) {
    let mut decoder = ThumbnailDecoder::new(&dll_path);
    while let Ok(request) = receiver.recv() {
        let result = decoder
            .as_mut()
            .map_err(|error| error.to_string())
            .and_then(|decoder| {
                decoder
                    .capture(
                        &request.url,
                        &request.request_headers,
                        request.bucket * THUMBNAIL_BUCKET_MS,
                    )
                    .map_err(|error| error.to_string())
            });
        if let Ok(bytes) = &result {
            if let Ok(mut cache) = cache().lock() {
                cache.insert(CachedFrame {
                    key: request.key,
                    source_key: request.source_key,
                    bucket: request.bucket,
                    bytes: bytes.clone(),
                });
            }
        } else if request.reply.is_none() {
            eprintln!(
                "background seek thumbnail failed at {}ms: {}",
                request.bucket * THUMBNAIL_BUCKET_MS,
                result.as_ref().unwrap_err()
            );
        }
        if let Some(reply) = request.reply {
            let _ = reply.send(result);
        }
    }
}

type MpvCreate = unsafe extern "C" fn() -> *mut c_void;
type MpvSetOptionString =
    unsafe extern "C" fn(*mut c_void, *const c_char, *const c_char) -> i32;
type MpvSetPropertyString =
    unsafe extern "C" fn(*mut c_void, *const c_char, *const c_char) -> i32;
type MpvInitialize = unsafe extern "C" fn(*mut c_void) -> i32;
type MpvCommand = unsafe extern "C" fn(*mut c_void, *const *const c_char) -> i32;
type MpvWaitEvent = unsafe extern "C" fn(*mut c_void, f64) -> *const MpvEvent;
type MpvDestroy = unsafe extern "C" fn(*mut c_void);

#[repr(C)]
struct MpvEvent {
    event_id: i32,
    error: i32,
    reply_userdata: u64,
    data: *mut c_void,
}

#[repr(C)]
struct MpvEventEndFile {
    reason: i32,
    error: i32,
}

struct ThumbnailDecoder {
    raw: *mut c_void,
    set_property: MpvSetPropertyString,
    command: MpvCommand,
    wait_event: MpvWaitEvent,
    destroy: MpvDestroy,
    output_dir: PathBuf,
    _library: Library,
}

impl ThumbnailDecoder {
    fn new(dll_path: &Path) -> Result<Self> {
        unsafe {
            let library = Library::new(dll_path).context("could not load libmpv-2.dll")?;
            let create = *library.get::<MpvCreate>(b"mpv_create\0")?;
            let set_option = *library.get::<MpvSetOptionString>(b"mpv_set_option_string\0")?;
            let set_property =
                *library.get::<MpvSetPropertyString>(b"mpv_set_property_string\0")?;
            let initialize = *library.get::<MpvInitialize>(b"mpv_initialize\0")?;
            let command = *library.get::<MpvCommand>(b"mpv_command\0")?;
            let wait_event = *library.get::<MpvWaitEvent>(b"mpv_wait_event\0")?;
            let destroy = *library.get::<MpvDestroy>(b"mpv_terminate_destroy\0")?;
            let raw = create();
            if raw.is_null() {
                bail!("mpv_create failed for thumbnail worker");
            }

            let output_dir = std::env::temp_dir().join(format!(
                "nuvio-thumbnail-worker-{}",
                std::process::id()
            ));
            let _ = fs::remove_dir_all(&output_dir);
            fs::create_dir_all(&output_dir)
                .context("could not create thumbnail worker directory")?;

            let try_set = |name: &str, value: &str| -> Result<bool> {
                let name = CString::new(name)?;
                let value = CString::new(value)?;
                Ok(set_option(raw, name.as_ptr(), value.as_ptr()) >= 0)
            };
            let set = |name: &str, value: &str| -> Result<()> {
                if !try_set(name, value)? {
                    bail!("libmpv rejected thumbnail option {name}");
                }
                Ok(())
            };
            let set_image = |suffix: &str, value: &str| -> Result<()> {
                if try_set(&format!("vo-image-{suffix}"), value)?
                    || try_set(&format!("image-{suffix}"), value)?
                {
                    return Ok(());
                }
                bail!("libmpv rejected thumbnail image option {suffix}")
            };

            set("config", "no")?;
            set("osc", "no")?;
            set("input-default-bindings", "no")?;
            set("input-vo-keyboard", "no")?;
            set("vo", "image")?;
            set("ao", "null")?;
            set("sub-auto", "no")?;
            set_image("format", "jpg")?;
            set_image("jpeg-quality", "80")?;
            set_image("outdir", &output_dir.to_string_lossy())?;
            set("vf", &format!("scale={THUMBNAIL_WIDTH}:-2"))?;
            set("keep-open", "yes")?;
            set("hr-seek", "yes")?;
            set("demuxer-readahead-secs", "0")?;
            for (name, value) in [
                ("vd-lavc-skiploopfilter", "all"),
                ("vd-lavc-skipidct", "nonref"),
                ("vd-lavc-fast", "yes"),
                ("ytdl", "no"),
                ("load-scripts", "no"),
                ("load-auto-profiles", "no"),
            ] {
                let _ = try_set(name, value)?;
            }
            set("network-timeout", "5")?;
            if initialize(raw) < 0 {
                destroy(raw);
                bail!("thumbnail worker initialisation failed");
            }

            Ok(Self {
                raw,
                set_property,
                command,
                wait_event,
                destroy,
                output_dir,
                _library: library,
            })
        }
    }

    fn capture(
        &mut self,
        url: &str,
        request_headers: &[String],
        position_ms: i64,
    ) -> Result<Vec<u8>> {
        self.clear_output()?;
        self.drain_events();
        self.set_property(
            "http-header-fields",
            &crate::player::encode_request_headers(request_headers),
        )?;
        let options = format!(
            "start={:.3},frames=1",
            position_ms.max(0) as f64 / 1000.0
        );
        self.command(&["loadfile", url, "replace", &options])?;

        let deadline = Instant::now() + CAPTURE_TIMEOUT;
        loop {
            if Instant::now() >= deadline {
                let _ = self.command(&["stop"]);
                bail!("timed out decoding thumbnail");
            }
            let event = unsafe { (self.wait_event)(self.raw, 0.1) };
            if event.is_null() {
                continue;
            }
            match unsafe { (*event).event_id } {
                1 => bail!("thumbnail worker shut down"),
                7 => {
                    let end = unsafe { (*event).data.cast::<MpvEventEndFile>() };
                    if !end.is_null() && unsafe { (*end).error } < 0 {
                        bail!("thumbnail source failed with libmpv error {}", unsafe {
                            (*end).error
                        });
                    }
                    return newest_jpeg(&self.output_dir);
                }
                _ => {}
            }
        }
    }

    fn set_property(&self, name: &str, value: &str) -> Result<()> {
        let name = CString::new(name)?;
        let value = CString::new(value)?;
        if unsafe { (self.set_property)(self.raw, name.as_ptr(), value.as_ptr()) } < 0 {
            bail!("libmpv rejected thumbnail property")
        }
        Ok(())
    }

    fn command(&self, values: &[&str]) -> Result<()> {
        let strings = values
            .iter()
            .map(|value| CString::new(*value))
            .collect::<std::result::Result<Vec<_>, _>>()?;
        let mut pointers = strings.iter().map(|value| value.as_ptr()).collect::<Vec<_>>();
        pointers.push(ptr::null());
        if unsafe { (self.command)(self.raw, pointers.as_ptr()) } < 0 {
            bail!("libmpv rejected thumbnail command")
        }
        Ok(())
    }

    fn drain_events(&self) {
        loop {
            let event = unsafe { (self.wait_event)(self.raw, 0.0) };
            if event.is_null() || unsafe { (*event).event_id } == 0 {
                break;
            }
        }
    }

    fn clear_output(&self) -> Result<()> {
        for entry in fs::read_dir(&self.output_dir)? {
            let path = entry?.path();
            if path
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("jpg"))
            {
                let _ = fs::remove_file(path);
            }
        }
        Ok(())
    }
}

impl Drop for ThumbnailDecoder {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            unsafe { (self.destroy)(self.raw) };
            self.raw = ptr::null_mut();
        }
        let _ = fs::remove_dir_all(&self.output_dir);
    }
}

fn newest_jpeg(output_dir: &Path) -> Result<Vec<u8>> {
    let entry = fs::read_dir(output_dir)
        .context("thumbnail directory could not be read")?
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("jpg"))
        })
        .max_by_key(|entry| {
            entry
                .metadata()
                .and_then(|metadata| metadata.modified())
                .unwrap_or(std::time::SystemTime::UNIX_EPOCH)
        })
        .context("thumbnail worker produced no frame")?;
    fs::read(entry.path()).context("thumbnail frame could not be read")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cached(source_key: u64, bucket: i64, marker: u8) -> CachedFrame {
        CachedFrame {
            key: frame_key(source_key, bucket),
            source_key,
            bucket,
            bytes: vec![marker],
        }
    }

    #[test]
    fn frame_keys_use_two_second_buckets() {
        let source = source_key("https://example/video", &["Authorization: token".into()]);
        assert_eq!(frame_key(source, bucket(2_001)), frame_key(source, bucket(3_999)));
        assert_ne!(frame_key(source, bucket(3_999)), frame_key(source, bucket(4_000)));
    }

    #[test]
    fn auth_headers_are_part_of_the_source_identity() {
        assert_ne!(
            source_key("https://example/video", &["Authorization: one".into()]),
            source_key("https://example/video", &["Authorization: two".into()]),
        );
    }

    #[test]
    fn nearest_frame_never_crosses_sources() {
        let mut cache = ThumbnailCache::default();
        cache.insert(cached(1, 2, 12));
        cache.insert(cached(2, 9, 29));
        assert_eq!(cache.nearest(1, 8), Some(vec![12]));
        assert_eq!(cache.nearest(3, 8), None);
    }

    #[test]
    fn exact_cache_hits_promote_the_frame_and_replace_duplicates() {
        let mut cache = ThumbnailCache::default();
        cache.insert(cached(1, 2, 12));
        cache.insert(cached(1, 2, 99));
        assert_eq!(cache.frames.len(), 1);
        assert_eq!(cache.exact(frame_key(1, 2)), Some(vec![99]));
    }
}
