import { useRef } from "react";
import type { ContentMeta } from "../bridge/types";
import { type ContinueWatchingCard, progressForCard, remainingLabel } from "./WatchStatus";
import { showTitleContextMenu } from "./TitleContextMenu";

export function ContinueWatchingRow({ cards, onSelect }: { cards: ContinueWatchingCard[]; onSelect(item: ContentMeta): void }) {
  const row = useRef<HTMLDivElement>(null); const drag = useRef({ active: false, moved: false, x: 0, scroll: 0 });
  return <section className="media-section continue-watching-section"><div className="section-heading"><div><h2>Continue watching</h2><p>Synced from Nuvio</p></div></div><div ref={row} className="continue-watching-row drag-scroll" onPointerDown={(event) => { if (event.button === 0 && row.current) drag.current = { active: true, moved: false, x: event.clientX, scroll: row.current.scrollLeft }; }} onPointerMove={(event) => { if (!drag.current.active || !row.current) return; const distance = event.clientX - drag.current.x; if (Math.abs(distance) > 12) drag.current.moved = true; if (drag.current.moved) row.current.scrollLeft = drag.current.scroll - distance; }} onPointerUp={() => { drag.current.active = false; }} onPointerLeave={() => { drag.current.active = false; }}>
    {cards.map((card) => { const video = card.video; const artwork = video?.thumbnail || card.item.background || card.item.banner || card.item.poster; const percent = progressForCard(card); const selected = video ? { ...card.item, selectedVideoId: video.id } : card.item; return <button className="continue-card" key={`${card.item.id}:${video?.id || card.progress?.videoId || "next"}`} onClick={() => { if (!drag.current.moved) onSelect(selected); drag.current.moved = false; }} onContextMenu={(event) => showTitleContextMenu(event, selected)}><div className="continue-card-art" style={artwork ? { backgroundImage: `url("${artwork.replaceAll('"', '%22')}")` } : undefined}><span className="continue-card-badge">{card.nextUp ? "Next up" : remainingLabel(card.progress)}</span><div className="continue-card-copy">{video?.season != null && video?.episode != null && <small>S{video.season} E{video.episode}</small>}<strong>{card.item.name}</strong>{video?.title && <span>{video.title}</span>}</div>{percent > 0 && <i className="continue-card-progress"><b style={{ width: `${percent}%` }} /></i>}</div></button>; })}
  </div></section>;
}
